blank_issues_enabled: false
contact_links:
  - name: FireHydrant Support
    url: https://support.firehydrant.com/hc/en-us
    about: For issues and feature requests related to the FireHydrant platform, please visit FireHydrant Support.